### ISSUE TITLE
F. F+MM-2.3H name

### ISSUE THREAD

**Issue by tabbassidaloii** [FAIRplus/Data-Maturity#19]
The definition given here is not consistent with what is provided in the DMM excel sheet ([FAIRplus Dataset Maturity Model_v0.2](https://docs.google.com/spreadsheets/d/1rEyUALCtoag_2rFd2NcS0qlRpPcOu-rIG37Vn062OVw/edit#gid=192612666)).
Based on the sheet, the definition for F. F+MM-2.3H is *Hosting environment offers the capability to browse related Datasets*.

**Comment by lauportell** [comment]
Hi Tooba,
yes indeed. This is not updated with the spreadsheet. We will update it once we finish the last changes.
